##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-box-centos7-develop"
    v.memory = "1024"

    v.customize [
      "modifyvm",           :id,
      "--hwvirtex",         "on",
      "--nestedpaging",     "on",
      "--largepages",       "on",
      "--ioapic",           "on",
      "--pae",              "on",
      "--paravirtprovider", "kvm",
    ]
  end
end

# Provisioning(s)
load  File.expand_path('common/UploadFiles.rb')

Vagrant.configure("2") do |config|
  config.vm.provision("setup-packages", type: "shell",
                      path: "provision/setup-packages.sh",
                      privileged: true)
  config.vm.provision("install-tools", type: "shell",
                      path: "provision/install-tools.sh",
                      privileged: false)
  config.vm.provision("cleanup", type: "shell",
                      path: "provision/cleanup.sh",
                      privileged: true)
  config.vm.synced_folder(".", "/vagrant", disabled: true)
end
