##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby


##########################################################################
##
##    Load Modules
##

load  File.expand_path('common/CommonCustomize.rb')
load  File.expand_path('common/UploadFiles.rb')


##########################################################################
##
##    Configuration
##

Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"
  customize_config(config)

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-box-rocky9-develop"
    v.memory = "1024"

    customize_vm_provider(v)
  end

  config.vm.synced_folder(".", "/vagrant", disabled: true)
end


##########################################################################
##
##    Customize Virtual Machine
##

# Provisioning(s)

Vagrant.configure("2") do |config|
  customize_config(config)

  provision_upload_files(config.vm)
end

Vagrant.configure("2") do |config|
  config.vm.provision("setup-packages", type: "shell",
                      path: "provision/setup-packages.sh",
                      privileged: true)
  # config.vm.provision("install-tools", type: "shell",
  #                     path: "provision/install-tools.sh",
  #                     privileged: false)
  config.vm.provision("cleanup", type: "shell",
                      path: "provision/cleanup.sh",
                      privileged: true)
end
